import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { reportsRepo, localToday } from '../db/repositories/reportsRepo';
import { ledgerRepo } from '../db/repositories/ledgerRepo';
import { borrowerRepo } from '../db/repositories/borrowerRepo';
import { loanRepo } from '../db/repositories/loanRepo';
import { paymentRepo } from '../db/repositories/paymentRepo';
import { penaltyRepo } from '../db/repositories/penaltyRepo';
import { sealRepo, type LedgerSeal } from '../db/repositories/sealRepo';
import { formatCurrency, formatDbDate, getDaysLate, getScheduleRemaining } from '../utils/financial';
import { canonicalMoney } from '../utils/money';
import { toSvgRects } from '../utils/qr';

/**
 * PDF documents.
 *
 * HTML → PDF through `expo-print`, then straight to the share sheet. Everything the treasurer
 * would otherwise copy out by hand (a borrower's statement, the month's report) becomes a file
 * they can send, print or file.
 *
 * Layout rules that matter in practice: A4 with real margins, zebra rows so `₱` figures do not
 * run together, and a footer with the generation date so a printed page can be traced back.
 */

const SKY = '#0284c7';
const DEEP = '#0c4a6e';
const SLATE = '#334155';

/** Escapes any text that goes into the HTML shell. */
function esc(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function documentShell(title: string, orgName: string, body: string, footnote: string): string {
  const generated = `${localToday()} · generated by Treasurer Vault`;
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>
  @page { size: A4; margin: 16mm 14mm; }
  * { box-sizing: border-box; }
  body { font-family: -apple-system, 'Segoe UI', Roboto, Arial, sans-serif; color: ${SLATE}; margin: 0; }
  h1 { font-size: 20px; color: ${DEEP}; margin: 0 0 2px 0; }
  h2 { font-size: 13px; color: ${SKY}; text-transform: uppercase; letter-spacing: 1px; margin: 22px 0 8px 0; }
  .sub { font-size: 12px; color: #64748b; }
  .head { border-bottom: 3px solid ${SKY}; padding-bottom: 12px; }
  table { width: 100%; border-collapse: collapse; margin-top: 6px; }
  th { background: #f0f9ff; color: ${DEEP}; font-size: 11px; text-transform: uppercase; text-align: left; padding: 7px 8px; border-bottom: 1px solid #bae6fd; }
  td { font-size: 12px; padding: 7px 8px; border-bottom: 1px solid #e2e8f0; }
  tr:nth-child(even) td { background: #f8fafc; }
  .num { text-align: right; white-space: nowrap; }
  .totals { margin-top: 10px; }
  .totals td { font-size: 12px; border: none; padding: 4px 8px; }
  .totals .label { color: #64748b; }
  .totals .value { text-align: right; font-weight: 700; color: ${DEEP}; }
  .grand { border-top: 2px solid ${DEEP}; font-size: 14px !important; }
  .cards { display: flex; gap: 10px; }
  .card { flex: 1; border: 1px solid #e2e8f0; border-radius: 8px; padding: 10px 12px; }
  .card .k { font-size: 10px; text-transform: uppercase; letter-spacing: .5px; color: #64748b; }
  .card .v { font-size: 16px; font-weight: 700; color: ${DEEP}; margin-top: 3px; }
  .pill { display: inline-block; font-size: 10px; padding: 2px 8px; border-radius: 999px; background: #e0f2fe; color: ${DEEP}; }
  .warn { color: #b91c1c; font-weight: 700; }
  .ok { color: #047857; font-weight: 700; }
  .mono { font-family: monospace; font-size: 10px; }
  .note { font-size: 11px; color: #92400e; background: #fffbeb; border: 1px solid #fde68a; border-radius: 8px; padding: 8px 10px; }
  .qrrow { display: flex; align-items: center; gap: 14px; margin-top: 10px; page-break-inside: avoid; }
  .qrhint { font-size: 10px; color: #64748b; line-height: 1.5; max-width: 260px; }
  .foot { margin-top: 26px; padding-top: 10px; border-top: 1px solid #e2e8f0; font-size: 10px; color: #94a3b8; }
</style>
</head>
<body>
  <div class="head">
    <h1>${esc(orgName)}</h1>
    <div class="sub">${esc(title)}</div>
  </div>
  ${body}
  <div class="foot">${esc(generated)}<br/>${esc(footnote)}</div>
</body>
</html>`;
}

/** Renders HTML to a PDF file and hands it to the share sheet. */
async function sharePdf(html: string, dialogTitle: string): Promise<void> {
  const { uri } = await Print.printToFileAsync({ html });
  if (!(await Sharing.isAvailableAsync())) {
    throw new Error(`The PDF was created at ${uri} but this device cannot share files.`);
  }
  await Sharing.shareAsync(uri, {
    mimeType: 'application/pdf',
    dialogTitle,
    UTI: 'com.adobe.pdf',
  });
}

const AGING_LABEL: Record<string, string> = {
  DUE_SOON: 'Due within 7 days',
  CURRENT: 'Due later',
  '1-30': '1–30 days late',
  '31-60': '31–60 days late',
  '61-90': '61–90 days late',
  '90+': 'Over 90 days late',
};

const CATEGORY_LABEL: Record<string, string> = {
  LOAN_REPAYMENT: 'Loan repayment',
  LOAN_DISBURSEMENT: 'Loan disbursement',
  DONATION: 'Donation',
  MEMBERSHIP_DUES: 'Membership dues',
  EXPENSE: 'Operating expense',
  OTHER: 'Other',
};


// ---------------------------------------------------------------------------
// Monthly report
// ---------------------------------------------------------------------------

export interface MonthlyReportInput {
  orgName: string;
  currencySymbol: string;
  monthLabel: string;
  /** `YYYY-MM` the report covers; used to find the published seal. Defaults to today's month. */
  period?: string;
}

/** The month-end report: cash, portfolio health, arrears, forecast, expenses and activity. */
export async function exportMonthlyReportPdf(input: MonthlyReportInput): Promise<void> {
  const [metrics, aging, risk, forecast, transactions, expenseRows] = await Promise.all([
    ledgerRepo.getMetrics(),
    reportsRepo.getAgingSchedule(),
    reportsRepo.getPortfolioRisk(),
    reportsRepo.getForecast(3),
    ledgerRepo.getTransactions(200),
    ledgerRepo.getExpenseBreakdown(),
  ]);

  const symbol = input.currencySymbol;
  const money = (v: number) => formatCurrency(v, symbol);

  const arrears = aging.filter((a) => a.bucket !== 'CURRENT' && a.bucket !== 'DUE_SOON');
  const arrearsTotal = canonicalMoney(arrears.reduce((sum, a) => sum + a.amount, 0));

  const agingRows = aging
    .map(
      (a) => `<tr>
        <td>${esc(AGING_LABEL[a.bucket])}</td>
        <td class="num">${a.installmentCount}</td>
        <td class="num">${a.borrowerCount}</td>
        <td class="num">${money(a.amount)}</td>
      </tr>`
    )
    .join('');

  const forecastRows = forecast.length
    ? forecast
        .map(
          (f) => `<tr>
            <td>${esc(f.period)}</td>
            <td class="num">${f.installmentCount}</td>
            <td class="num">${money(f.expected)}</td>
          </tr>`
        )
        .join('')
    : '<tr><td colspan="3">No scheduled collections yet.</td></tr>';

  const expenseList = expenseRows.length
    ? expenseRows
        .map(
          (e) => `<tr>
            <td>${esc(e.description || '—')}</td>
            <td>${esc(CATEGORY_LABEL[e.category] ?? e.category)}</td>
            <td class="num">${money(e.total)}</td>
          </tr>`
        )
        .join('')
    : '<tr><td colspan="3">No expenses recorded.</td></tr>';

  const recentRows = transactions
    .slice(0, 25)
    .map(
      (t) => `<tr>
        <td>${esc(formatDbDate(t.transactionDate))}</td>
        <td>${esc(CATEGORY_LABEL[t.category] ?? t.category)}${t.voidedAt ? ' <span class="warn">(void)</span>' : ''}</td>
        <td>${esc(t.description || '—')}</td>
        <td class="num">${t.type === 'INFLOW' ? '+' : '−'}${money(t.amount)}</td>
      </tr>`
    )
    .join('');

  // The seal the members were given for this month, if the treasurer has closed it.
  let seal: LedgerSeal | null = null;
  try {
    seal = await sealRepo.getLatestForPeriod(input.period ?? localToday().slice(0, 7));
  } catch {
    // A database without the seals table still produces a valid report.
    seal = null;
  }

  const body = `
    <h2>Cash position</h2>
    <div class="cards">
      <div class="card"><div class="k">Liquid cash</div><div class="v">${money(metrics.liquidCash)}</div></div>
      <div class="card"><div class="k">Total in</div><div class="v">${money(metrics.totalInflows)}</div></div>
      <div class="card"><div class="k">Total out</div><div class="v">${money(metrics.totalOutflows)}</div></div>
    </div>

    <h2>Portfolio</h2>
    <div class="cards">
      <div class="card"><div class="k">Outstanding</div><div class="v">${money(metrics.outstandingPrincipal)}</div></div>
      <div class="card"><div class="k">Overdue</div><div class="v ${metrics.overdueAmount > 0 ? 'warn' : 'ok'}">${money(metrics.overdueAmount)}</div></div>
      <div class="card"><div class="k">Portfolio at risk</div><div class="v">${risk.parPercent.toFixed(1)}%</div></div>
    </div>
    <table class="totals">
      <tr><td class="label">Active loans</td><td class="value">${risk.activeLoanCount}</td></tr>
      <tr><td class="label">Loans behind schedule</td><td class="value">${risk.atRiskLoanCount}</td></tr>
      <tr><td class="label">Borrowers with an active loan</td><td class="value">${metrics.activeBorrowersCount}</td></tr>
      <tr><td class="label">Expected interest (unearned)</td><td class="value">${money(metrics.expectedInterest)}</td></tr>
      <tr><td class="label">Collections this month</td><td class="value">${money(metrics.totalCollectedThisMonth)}</td></tr>
    </table>

    <h2>Aging of receivables</h2>
    <table>
      <thead><tr><th>Bucket</th><th class="num">Installments</th><th class="num">Borrowers</th><th class="num">Amount</th></tr></thead>
      <tbody>${agingRows}</tbody>
    </table>
    <table class="totals">
      <tr><td class="label grand">Total arrears</td><td class="value grand">${money(arrearsTotal)}</td></tr>
    </table>

    <h2>Expected collections — coming months</h2>
    <table>
      <thead><tr><th>Month</th><th class="num">Installments</th><th class="num">Expected</th></tr></thead>
      <tbody>${forecastRows}</tbody>
    </table>

    <h2>Expenses by category</h2>
    <table>
      <thead><tr><th>Description</th><th>Category</th><th class="num">Amount</th></tr></thead>
      <tbody>${expenseList}</tbody>
    </table>

    <h2>Recent ledger activity</h2>
    <table>
      <thead><tr><th>Date</th><th>Category</th><th>Description</th><th class="num">Amount</th></tr></thead>
      <tbody>${recentRows}</tbody>
    </table>

    <h2>Published seal for this month</h2>
    ${
      seal
        ? `<table class="totals">
             <tr><td class="label">Seal code</td><td class="value">${esc(seal.sealCode)}</td></tr>
             <tr><td class="label">Sealed on</td><td class="value">${esc(formatDbDate(seal.createdAt))}</td></tr>
             <tr><td class="label">Entries covered</td><td class="value">${seal.auditCount}</td></tr>
             <tr><td class="label">Chain head</td><td class="value mono">${esc(seal.chainHead.slice(0, 32))}…</td></tr>
           </table>
           <div class="qrrow">${toSvgRects(seal.sealCode, 132)}<div class="qrhint">Scan to compare against the seal the members received. A matching code means this report was not rewritten after the month was closed.</div></div>`
        : `<p class="note">This month has not been sealed yet. Sealing it (Reports → Sealed months) fixes the figures and prints a code the members can check.</p>`
    }
  `;

  await sharePdf(
    documentShell(
      `Monthly report — ${input.monthLabel}`,
      input.orgName,
      body,
      'Figures are derived from the installment schedule and the ledger. Voided entries are excluded from totals.'
    ),
    'Share monthly report'
  );
}

// ---------------------------------------------------------------------------
// Borrower statement of account
// ---------------------------------------------------------------------------

export interface StatementInput {
  borrowerId: string;
  /** When omitted, the borrower's newest loan is used. */
  loanId?: string;
  orgName: string;
  currencySymbol: string;
}

/**
 * Statement of account for one loan: the terms, the amortization schedule with what has actually
 * been paid against each installment, and the payment history including any voids.
 */
export async function exportLoanStatementPdf(input: StatementInput): Promise<void> {
  const borrower = await borrowerRepo.getById(input.borrowerId);
  if (!borrower) throw new Error('That borrower is no longer in the book.');

  const loans = await loanRepo.getLoansByBorrower(input.borrowerId);
  if (loans.length === 0) throw new Error('That borrower has no loan to report on.');

  const loan = (input.loanId ? loans.find((l) => l.id === input.loanId) : loans[0]) ?? loans[0];

  const [schedules, payments] = await Promise.all([
    loanRepo.getSchedulesByLoanId(loan.id),
    paymentRepo.getPaymentsByLoan(loan.id),
  ]);

  const symbol = input.currencySymbol;
  const money = (v: number) => formatCurrency(v, symbol);

  const scheduleRows = schedules
    .map((s) => {
      const remaining = getScheduleRemaining(s);
      const late = s.status !== 'PAID' ? getDaysLate(s.dueDate) : 0;
      const status =
        s.status === 'PAID'
          ? '<span class="pill">Paid</span>'
          : late > 0
            ? `<span class="warn">${late}d late</span>`
            : 'Pending';
      return `<tr>
        <td class="num">#${s.installmentNumber}</td>
        <td>${esc(formatDbDate(s.dueDate))}</td>
        <td class="num">${money(s.expectedAmount)}</td>
        <td class="num">${money(s.paidAmount)}</td>
        <td class="num">${money(remaining)}</td>
        <td>${status}</td>
      </tr>`;
    })
    .join('');

  const paymentRows = payments.length
    ? payments
        .map(
          (p) => `<tr>
            <td>${esc(formatDbDate(p.paidAt))}</td>
            <td>${esc(p.paymentMethod)}</td>
            <td>${esc(p.referenceNo || '—')}</td>
            <td>${p.voidedAt ? '<span class="warn">VOID</span>' : 'Posted'}</td>
            <td class="num">${p.voidedAt ? '—' : money(p.amountPaid)}</td>
          </tr>`
        )
        .join('')
    : '<tr><td colspan="5">No payments recorded yet.</td></tr>';

  const paidTotal = canonicalMoney(
    payments.filter((p) => !p.voidedAt).reduce((s, p) => s + p.amountPaid, 0)
  );

  // Penalties belong on the statement: they are money the borrower is being asked to pay, and an
  // open fine is the single most likely reason a collection visit turns into an argument.
  let penaltyRows = '<tr><td colspan="6">No penalties assessed.</td></tr>';
  let penaltyOutstanding = 0;

  try {
    const charges = await penaltyRepo.getChargesForLoan(loan.id);
    if (charges.length > 0) {
      penaltyRows = charges
        .map((charge) => {
          const open = canonicalMoney(charge.amount - charge.paidAmount);
          if (!charge.waivedAt) penaltyOutstanding = canonicalMoney(penaltyOutstanding + open);
          return `<tr>
            <td class="num">#${esc(charge.installmentNumber ?? '—')}</td>
            <td>${charge.waivedAt ? '<span class="warn">WAIVED</span>' : esc(charge.daysLate + 'd late')}</td>
            <td class="num">${money(charge.amount)}</td>
            <td class="num">${money(charge.paidAmount)}</td>
            <td class="num">${charge.waivedAt ? '—' : money(open)}</td>
            <td>${esc(charge.waivedReason || (charge.waivedAt ? 'waived' : 'assessed'))}</td>
          </tr>`;
        })
        .join('');
    }
  } catch {
    // A database without the penalty tables still produces a valid statement.
    penaltyRows = '<tr><td colspan="6">No penalties assessed.</td></tr>';
  }

  const body = `
    <h2>Borrower</h2>
    <table class="totals">
      <tr><td class="label">Name</td><td class="value">${esc(borrower.fullName)}</td></tr>
      <tr><td class="label">Phone</td><td class="value">${esc(borrower.phoneNumber)}</td></tr>
      <tr><td class="label">Address</td><td class="value">${esc(borrower.address || '—')}</td></tr>
      <tr><td class="label">Category</td><td class="value">${esc(borrower.categoryTag || 'General')}</td></tr>
    </table>

    <h2>Loan terms</h2>
    <table class="totals">
      <tr><td class="label">Loan reference</td><td class="value">${esc(loan.id)}</td></tr>
      <tr><td class="label">Principal</td><td class="value">${money(loan.principalAmount)}</td></tr>
      <tr><td class="label">Interest</td><td class="value">${esc(loan.interestRate)}% (${esc(loan.interestType)})</td></tr>
      <tr><td class="label">Schedule</td><td class="value">${esc(loan.frequency)} × ${esc(loan.termCount)}</td></tr>
      <tr><td class="label">Released</td><td class="value">${esc(formatDbDate(loan.startDate))}</td></tr>
      <tr><td class="label">Maturity</td><td class="value">${esc(formatDbDate(loan.endDate))}</td></tr>
      <tr><td class="label">Total payable</td><td class="value">${money(loan.totalPayable)}</td></tr>
      <tr><td class="label">Paid to date</td><td class="value">${money(paidTotal)}</td></tr>
      <tr><td class="label grand">Balance</td><td class="value grand">${money(loan.remainingBalance)}</td></tr>
      <tr><td class="label">Penalties outstanding</td><td class="value">${money(penaltyOutstanding)}</td></tr>
      <tr><td class="label">Total collectable</td><td class="value">${money(canonicalMoney(loan.remainingBalance + penaltyOutstanding))}</td></tr>
    </table>

    <h2>Installment schedule</h2>
    <table>
      <thead><tr><th class="num">#</th><th>Due date</th><th class="num">Expected</th><th class="num">Paid</th><th class="num">Remaining</th><th>Status</th></tr></thead>
      <tbody>${scheduleRows}</tbody>
    </table>

    <h2>Penalties assessed</h2>
    <table>
      <thead><tr><th class="num">Installment</th><th>Lateness</th><th class="num">Charged</th><th class="num">Paid</th><th class="num">Open</th><th>Note</th></tr></thead>
      <tbody>${penaltyRows}</tbody>
    </table>

    <h2>Payment history</h2>
    <table>
      <thead><tr><th>Date</th><th>Method</th><th>Reference</th><th>Status</th><th class="num">Amount</th></tr></thead>
      <tbody>${paymentRows}</tbody>
    </table>
  `;

  await sharePdf(
    documentShell(
      `Statement of account — ${loan.id}`,
      input.orgName,
      body,
      'Generated from the ledger on this device. Voided payments are listed but excluded from the balance.'
    ),
    'Share statement of account'
  );
}
